// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7NmBvNTGpzWmm220FL-QSPIOKnEBUyg',
    appId: '1:405455912559:web:21e14de5d76cf008c2579a',
    messagingSenderId: '405455912559',
    projectId: 'gradition-850aa',
    authDomain: 'gradition-850aa.firebaseapp.com',
    storageBucket: 'gradition-850aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2UNWxoCaD3Hspb-t6KOHYEw5hg6jVTk',
    appId: '1:405455912559:android:dbdc15ca6ec259efc2579a',
    messagingSenderId: '405455912559',
    projectId: 'gradition-850aa',
    storageBucket: 'gradition-850aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfoQfeLWbdqW71-pcEHFBpDk0iTEFh2U',
    appId: '1:405455912559:ios:2d0c566f5d0720d0c2579a',
    messagingSenderId: '405455912559',
    projectId: 'gradition-850aa',
    storageBucket: 'gradition-850aa.appspot.com',
    iosClientId: '405455912559-co4ui3s84693bitesjbs3rqd1ts07tq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinscantech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpfoQfeLWbdqW71-pcEHFBpDk0iTEFh2U',
    appId: '1:405455912559:ios:2d0c566f5d0720d0c2579a',
    messagingSenderId: '405455912559',
    projectId: 'gradition-850aa',
    storageBucket: 'gradition-850aa.appspot.com',
    iosClientId: '405455912559-co4ui3s84693bitesjbs3rqd1ts07tq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinscantech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7NmBvNTGpzWmm220FL-QSPIOKnEBUyg',
    appId: '1:405455912559:web:813aad04f6ac4902c2579a',
    messagingSenderId: '405455912559',
    projectId: 'gradition-850aa',
    authDomain: 'gradition-850aa.firebaseapp.com',
    storageBucket: 'gradition-850aa.appspot.com',
  );
}
